### PR TITLE
Add TypeScript declaration file from documentation.

### PR DESCRIPTION
**Pull request by aholmes**
To support wider adoption, I create this TypeScript declaration file.

As far as I was able to determine, these definitions match the API documentation in `readme.md`.

### CODE REVIEW

**Comment by JonAbrams** [comment]
That's amazing. Nice work, thanks!

What would happen if work on the library continues, but this doesn't get updated?

**Comment by aholmes** [comment]
Unfortunately maintaining TypeScript declaration files is very much a manual process. As you can see in the second commit I added, I noticed one of the tests failed, and `xeger()` needed to support sending just an object as the first parameter. That wasn't the case when I made the first commit.

**Comment by JonAbrams** [comment]
I didn't see any tests fail. I imagine the mocha tests I wrote ignore the TS file. Is this testable somehow?

**Comment by aholmes** [comment]
Not directly, no. TypeScript definition files aren't intended to exist for execution. They exist purely for editors and the TypeScript compiler to provide type checking for libraries that aren't written in TypeScript.

For example, if someone wanted to use xeger.js in their TypeScript application, xeger.d.ts would provide information to that TypeScript application about how to use xeger.js. It doesn't affect xeger.js itself.

That said, it looks like there may be a project to enable testing of .d.ts files, but I would have to add more files to your project. :) https://www.npmjs.com/package/typescript-definition-tester

**Comment by JonAbrams** [comment]
I'm curious, do editors take advantage of this file even if it's for writing JS?

**Comment by aholmes** [comment]
No, however one nice thing about TypeScript is that all JavaScript is also valid TypeScript.

You could easily take advantage of this .d.ts file by naming your script `script.ts` (the extension is important) and adding a reference to the file: `/// <reference path="xeger.d.ts" />`.

**Comment by JonAbrams** [comment]
I'm closing this since your fork handles this quite nicely now.

**Pull request closed without merging**
